### ISSUE TITLE
meaningful filename at releases

### ISSUE THREAD

**Issue by ghost** [XiangRongLin/NewPipe-preuinified#8]
<img width="200" src="https://user-images.githubusercontent.com/415238/135146585-08e8f6df-bbd5-4a82-bcb1-140ec8fff80a.png" /><br/>

instead of `app-release.apk`, 
something like `NewPipe-preuinified_v0.21.10.apk`.
its a small thing, but it helps when organising old files on my computer and phone.  
using the package name is perfectly fine as well, better even (`org.schabi.newpipe.preunified_v0.21.10.apk` ), 
(I'm actually manually querying the package name with `aapt dump badging %~1 | grep "package:" | sed -n "s@package: name='\([^^']\+\).*'@\1@p"` and manually renaming it each time..).

**Comment by XiangRongLin** [comment]
Changing the filename to start with `NewPipe-preuinified_` is very simple. One just has to change this line here where `app-release.apk` stands and line 39 https://github.com/XiangRongLin/NewPipe-preuinified/blob/pre-unified/.github/workflows/release.yml#L34

Also adding the version number requires some shell logic to extract the version from the tag name. If I remember correctly github only provides the tags as `origin/refs/v0.x.y` where the front part would have to be cut off.

Since you seems more proficient in shell then me, feel free to shoot me a PR. Otherwise I'll take a look at it sometime in the future
